object Versions {

    const val appCompat = "1.3.1"
    const val gradlePlugin = "4.2.1"
    const val kotlin = "1.5.0"//"1.3.72"
    const val retrofit = "2.9.0"
    const val gson = "2.9.0"
    const val gsonConverter = "2.9.0"
    const val okHttpLogging = "4.8.1"
    const val coroutinesCore = "1.4.1"
    const val coroutinesAndroid = "1.4.1"
    const val koin = "3.0.2"
    const val lifeCycleViewModel = "2.3.1"
    const val lifeCycleRuntime = "2.4.0-alpha02"
    const val material = "1.4.0"
    const val constraintLayout = "2.1.2"
    const val ktxCore = "1.5.0"
    const val navigationGraph = "2.2.0"
    const val glide = "4.13.0"
}